### ISSUE TITLE
Feature Request: annotating rule for namespaces/excludedNamespaces

### ISSUE THREAD

**Issue by dulltz** [plexsystems/konstraint#106]
Like https://github.com/plexsystems/konstraint/issues/93, I'd like to support annotating rules that generate [`spec.match.namespaces` and `spec.match.excludedNamespaces`](https://github.com/open-policy-agent/gatekeeper/tree/1459e2f8eae495a0a34c529da794b3f1dda486d4#constraints).

## Examples

```rego
# @namespaces kube-system gatekeeper-system
package foo

import data.lib.core
...
```
↓
```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Foo
metadata:
  name: foo
spec:
  match:
    namespaces:
      - kube-system
      - gatekeeper-system
```

---

```rego
# @ excludednamespaces kube-system gatekeeper-system
package foo

import data.lib.core
...
```
↓
```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Foo
metadata:
  name: foo
spec:
  match:
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
```
