### ISSUE TITLE
data.parameters generates errors while loading the YAML template in Gatekeeper

### ISSUE THREAD

**Issue by JonnieDoe** [plexsystems/konstraint#108]
The `data.parameters` generates an error while loading the generated YAML template in Gatekeeper.
https://github.com/plexsystems/konstraint/blob/279945ba1f170f4bd8d6c9a2f586a781736ace7c/examples/lib/core.rego#L47-L49 
```yaml
- errors:
    - code: create_error
      message: 'check refs failed on module {libs.admission.k8s.gatekeeper.sh.K8sValidPodDisruptionBudget["lib_0"]}:
        disallowed ref data.parameters'
```

I think we need to update to use [replicate data](https://github.com/open-policy-agent/gatekeeper/blob/master/README.md#replicating-data)
