### ISSUE TITLE
Bug: .spec.match.kinds[]kinds is duplicated when the same kinds are given

### ISSUE THREAD

**Issue by dulltz** [plexsystems/konstraint#114]
When specify multi targets with a same kind at `@kinds` annotating rule, konstraint creates duplicated item at `constraint.spec.match.kinds[]kinds`.

## Example

```rego
# @title example
#
# @kinds networking.k8s.io/Ingress extensions/Ingress
package example
...
```

From the above rego code, `konstraint create` generates the following YAML.

```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Example
metadata:
  name: example
spec:
  match:
    kinds:
    - apiGroups:
      - networking.k8s.io
      - extensions
      kinds:
      - Ingress
      - Ingress # 👈 duplicated item
```

## Expected behavior

When a duplicate kind is specified, I want to remove the duplicate from the `example.spec.match.kinds[]kinds`.
