### ISSUE TITLE
Parameters issue.

### ISSUE THREAD

**Issue by devopsop** [plexsystems/konstraint#123]
Greetings,,

I want to have a ContraintTemplate with the following parameters:
```
  parameters:
    limits:
      cpu: "4"
      memory: "8Gi"
    requests:
      cpu: "2"
      memory: "4Gi"
```
I have tried adding at the top of my rego file:
```
# @parameter limits.cpu string
# @parameter limits.memory string
# @parameter rquests.cpu string
# @parameter requests.memory string
```
But I get the following error:
`Error: get violations: parse directory: count of @parameter tags does not match parameter count`

Perhaps I am doing something wrong... am I on the right track with this?
