### ISSUE TITLE
Request: Generate the sync gatekeeper config based on policies with data.inventory

### ISSUE THREAD

**Issue by garethahealy** [plexsystems/konstraint#16]
Use case: I want to be able to auto-generate the sync config (https://github.com/open-policy-agent/gatekeeper#replicating-data) for any kinds which are used via `data.inventory`.

For example, i have a policy which checks all Services have a ServiceMonitor, i.e.:
`data.inventory.namespace[service.metadata.namespace]["monitoring.coreos.com/v1"]["ServiceMonitor"]`

Firstly, does it sound like a good fit for konstraint? and secondly, possible?

**Comment by jpreese** [comment]
I haven't used that feature of Gatekeeper yet, but looking over the documentation it definitely seems possible. We would just need to look for `data.inventory` in the policies, and then we can pull out the kinds/groups/versions from those.

It also seems like a potential fit. Is the assumption that if you put `data.inventory` into your policy that you would _always_ add it to the Gatekeeper config as well? In that case, then I think it's a clear win.

**Comment by garethahealy** [comment]
`It also seems like a potential fit. Is the assumption that if you put data.inventory into your policy that you would always add it to the Gatekeeper config as well? In that case, then I think it's a clear win.`

Yes, i'd always expect it to be in the sync block if you are accessing `data.inventory`

**Comment by jpreese** [comment]
Ok, thanks for bringing this up. I'll do some additional investigation, but it seems like a valid request.

For where the config file would be rendered to, what would best fit your use case? Current directory if a `--config-path` (suggestion) flag is not set?

**Comment by garethahealy** [comment]
Yes, that sounds fine.

**Comment by jpreese** [comment]
@jalseth @garethahealy 

It would be interesting to see if we could use the [--data](https://www.conftest.dev/options/#-data) argument with [Conftest](https://github.com/open-policy-agent/conftest) to mimic `data.inventory`.

Given a bundle of Kubernetes resource(s), create a `.yaml` file with an `inventory:` header. Users would not create this `inventory` yaml, but rather it would be auto-generated from the Kubernetes resources that are to be deployed.

Then by passing in that yaml during the policy evaluation ( `conftest -d somefile.yaml` ), the `data.inventory` rule is applicable to not only Gatekeeper evaluations, but Conftest as well.

**Comment by jpreese** [comment]
Played with this for a little today, and early testing seems promising.

example data file (would be generated from the actual resources in the `gatekeeper-system` namespace):
```yaml
inventory:
  namespace:
    gatekeeper-system:
      v1:
        Service:
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              gatekeeper.sh/system: "yes"
              gatekeeper.sh/operation: "audit"
            name: gatekeeper-audit-metrics-service
            namespace: gatekeeper-system
          spec:
            ports:
              - port: 8889
                name: audit-metrics
                targetPort: 8888
            selector:
              app.kubernetes.io/instance: gatekeeper
              app.kubernetes.io/name: gatekeeper
              control-plane: audit-controller
              gatekeeper.sh/operation: audit
              gatekeeper.sh/system: "yes"
```
[[data.yaml]]

Using @garethahealy 's `data.inventory` based policy:
https://github.com/redhat-cop/rego-policies/blob/master/policy/ocp/requiresinventory/deployment-has-matching-service/src.rego

```shall
$ conftest test - -p policy/cluster --all-namespaces -d policy/cluster/data/data.yaml
```
