### ISSUE TITLE
constraint not generated

### ISSUE THREAD

**Issue by olivier-mauras** [plexsystems/konstraint#169]
I'm using `konstraint create` to generate template.yaml and constraint.yaml from a simple rego file.

``` rego
# @enforcement deny
# @kinds core/Namespace
# @parameter protected array string
package gnamespaceprotect

violation[{"msg": msg, "details": {}}] {
    input.review.operation == "DELETE"
    input.review.object.metadata.name == input.parameters.protected[_]
    msg := "This namespace is protected and cannot be deleted"
}
```
The resulting template.yaml is fine
``` yaml
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  creationTimestamp: null
  name: namespaceprotect
spec:
  crd:
    spec:
      names:
        kind: NamespaceProtect
      validation:
        openAPIV3Schema:
          properties:
            protected:
              items:
                type: string
              type: array
  targets:
  - rego: |-
      package gnamespaceprotect

      violation[{"msg": msg, "details": {}}] {
          input.review.operation == "DELETE"
          input.review.object.metadata.name == input.parameters.protected[_]
          msg := "This namespace is protected and cannot be deleted"
      }
    target: admission.k8s.gatekeeper.sh
status: {}
```
Sadly no constaint.yaml is generated.
The create command completes without any error... Am I missing something obvious?
