### ISSUE TITLE
Generate descriptions for parameters

### ISSUE THREAD

**Issue by stek29** [plexsystems/konstraint#273]
Currently there's no way to generate `@parameter`s with description

I'm not sure what would be the best way to document them, but this might be an option:

having:
```rego
# @parameter exemptImages array string
#  Any container that uses an image that matches an entry in this list will be excluded
#  from enforcement. Prefix-matching can be signified with `*`. For example: `my-image-*`.
```

generate:
```yaml
properties:
  exemptImages:
    description: >-
      Any container that uses an image that matches an entry in this list will be excluded
      from enforcement. Prefix-matching can be signified with `*`. For example: `my-image-*`.
    type: array
    items:
      type: string
```
