### ISSUE TITLE
Question: What value does the current doc format give?

### ISSUE THREAD

**Issue by garethahealy** [plexsystems/konstraint#5]
The current doc format is as follows:

> |API Groups|Kinds|Description|
> |---|---|---|
> |apps, core|DaemonSet, Deployment, StatefulSet, Pod|Container images can not use the latest tag.|
> |apps, core|DaemonSet, Deployment, StatefulSet, Pod|EmptyDir volume mounts must specify a size limit.|

But am not sure what value that gives you, since that table could be interpreted as:

All of these API Groups, support all of these Kinds. i.e.:
apps -> DaemonSet, Deployment, StatefulSet, Pod
core -> DaemonSet, Deployment, StatefulSet, Podcore

Which is not true. Wouldnt it be easier if the table just listed the whole apiVersion/kind? i.e.:

> |API Groups/Kinds|Description|
> |---|---|
> |apps/DaemonSet, apps/Deployment, apps/StatefulSet, core/Pod|Container images can not use the latest tag.|
> |apps/DaemonSet, apps/Deployment, apps/StatefulSet, core/Pod|EmptyDir volume mounts must specify a size limit.|

This is just my view, maybe I am missing the benefit of splitting them out.

**Comment by jpreese** [comment]
The initial reasoning is due to how `Gatekeeper` does its [matching with Constraints](https://github.com/open-policy-agent/gatekeeper#constraints). So the table would translate to

```yaml
spec:
  match:
    kinds:
      - apiGroups: ["", "apps"]
        kinds: ["DaemonSet", "Deployment", "StatefulSet", "Pod"]
```

But now that you mention it, the `kinds` field should support multiple entries, so it might be better if the end result was:

```yaml
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - DaemonSet
      - Deployment
      - StatefulSet
```
