### ISSUE TITLE
Re-generation of existing ConstraintTemplates and Constraints overwrites fields

### ISSUE THREAD

**Issue by phomein** [plexsystems/konstraint#56]
Hello, great tool and idea btw.

When running `konstraint create` on rules that already have a template.yaml and a constraint.yaml, certain fields are removed or overwritten, namely

* the validation.openAPIV3Schema field for templates
* the spec.match.kinds and spec.parameters fields for constraints

It'd be great if these fields could be left alone. 

A cursory glance at getConstraintTemplate in create.go seems to show the validation field isn't included in the schema, though I'm a bit uncertain what's going on with getConstraint.

I've yet to write any golang, but I might be able to take a stab at a PR for this maybe next week or the following once work gets less busy

**Comment by jpreese** [comment]
This sounds reasonable to me. Let myself or @jalseth know if you need any help working on this if you decide to pick it up 👍

**Comment by Pierre-Mike** [comment]
Yes I'm having the same issue here
with, 

```yaml
  excludedNamespaces:
      - gatekeeper-system
      - kube-system
      - istio-system
```

**Comment by jalseth** [comment]
We now (as of a few minutes ago) support generating the OpenAPIV3Schema validation using the `@parameter` tag in the header comment block, so that is the preferred way forward for that item.

@Pierre-Mike Typically, when people want to exclude the `*-system` namespaces, they want to apply that for all of their policies, and not just one. In that case, it would be best to use the `Config` CRD for Gatekeeper (https://github.com/open-policy-agent/gatekeeper/#exempting-namespaces-from-gatekeeper) which will apply globally within the cluster. Does that work for your use case or are you trying to add these exemptions for individual policies?

**Comment by rawc0der** [comment]
Hi @jalseth,
Can you please give an example of how to include the schema spec using `@parameter` annotation?
Currently in order to generate `validation.openAPIV3Schema` field for the constraint templates, I'm using scripting utilities like **yq/jq** to decorate the final resources (Schemas for a policy is extracted from external source).

Is it possible to allow passing a json string as a `@schema` annotation and merge the structural schema in the generated resource?

Example ./mypolicy.rego
```
# @title mypolicy 
#
# @kinds apps/DaemonSet apps/Deployment apps/StatefulSet core/Pod
# @parameter apiVersion string
# @parameter kind string
# @parameter metadata object
# @parameter spec object
$ @schema '{ \"properties\": {\"apiVersion\": {\"description\": \"...\",\"type\": \"string\"},\"kind\": {\"description\": \"...\",\"type\": \"string\"},\"metadata\": {\"type\": \"object\",\"properties\": {  \"labels\": { \"type\": \"object\" }}},\"spec\": {\"type\": \"object\",\"properties\": \"....\"} }}'
package mypolicy 

....
```

Generated ./template_Mypolicy.yaml
```
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: mypolicy
spec:
  crd:
    spec:
      names:
        kind: Mypolicy
    validation:
        openAPIV3Schema:
            properties:
                apiVersion:
                    description: "..."
                    type: string
                kind:
                    description: "..."
                    type: string
                metadata:
                    type: object
                    properties:
                        labels:
                            type: object
                spec:
                    type: object
                    properties:
                        ....

  targets:
    - libs:  ...
```

Any thoughts?
