### ISSUE TITLE
Feature request: Add support for policies that use Gatekeeper's input parameters

### ISSUE THREAD

**Issue by Cellebyte** [plexsystems/konstraint#78]
Hey Guys,
sorry for bothering you with this question.

If I currently have something like this here.
How is it possible to have those parameters defined in a costrainttemplate?

```rego
package blacklist_label

default deny = false
default system_regex = "^system:.*" 
system_regex = input.parameters.system_regex

default system_auth = "^system:authenticated$"

label_regex := input.parameters.label_regex

matching_label_keys = value {
    some key
    value := count({key | _ = input.review.object.metadata.labels[key]; re_match(label_regex, key)})
}

user_is_authenticated = value {
    value := count({group | group = input.review.userInfo.groups[_]; re_match(system_auth, group)})
}

# user_is_system is true if regex matches...
user_is_system = value {
    value := count({group | group = input.review.userInfo.groups[_]; re_match(system_regex, group)})
}

deny {
    matching_label_keys > 0
    not user_is_system > 0
}

violation[{"msg": msg, "details": details}] {
    deny
    details := input.review.object.metadata.labels
    msg := sprintf("Please ensure that the label key does not match the regex: %v", [label_regex])
}
```

The Template should generate something like this here.
```yaml
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: blacklist_label
spec:
  crd:
    spec:
      names:
        kind: BlacklistLabel
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            label_regex:
              type: string
            system_regex:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |

```
