### ISSUE TITLE
Feature Request:  Add support for extracting parameters from Annotations 

### ISSUE THREAD

**Issue by rawc0der** [plexsystems/konstraint#90]
Currently the library allows extracting parameters from Gatekeeper's Constraint resources using  `input.parameters`  and data passed to Conftest tool as `data.parameters` fields.
I would like to propose adding an extra layer of parameterisation, which can be simply extracted from the resource level annotations.

Example usage for annotation level parameters:

```
kind: Deployment
metadata:
  name: MyDeployment
spec:
....
  template:
    metadata:
      annotations:
          konstraint.policies/parameters.policyID: '{"json":"custom-data"}'
          konstraint.policies/ignore: "policyID1,policyID2"
```

```
import data.lib.parameters
parameters = parameters.parameters(policyID)
```

Using `policyID` as a key here, because multiple policies can have the same input and will keep the data in distinct values for each policy.

This feature serves multiple use-cases, one which is very interesting is allowing to exclude policies from evaluation if there is a kill switch in the annotations/parameters.
I am submitting a corresponding PR and am open to respond to any reviews and adjust code accordingly.
